services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: /bin/bash
