services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/workspace
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=:0
    working_dir: /workspace
    stdin_open: true
    tty: true
    command: /bin/bash
    depends_on:
      - mysql
  
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: uth1234
      MYSQL_DATABASE: triangulos
      MYSQL_USER: Developer
      MYSQL_PASSWORD: uth1234
    ports:
      - "3306:3306"
    volumes:
      - ./database:/docker-entrypoint-initdb.d
